In [1]:
import pandas as pd
df=pd.read_csv("C:/Users/ncssa/Downloads/bus_routes.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12184 entries, 0 to 12183
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Route_Name         12184 non-null  object
 1   Route_Link         12184 non-null  object
 2   Bus_Name           12184 non-null  object
 3   Bus_Type           12184 non-null  object
 4   Departing_Time     12184 non-null  object
 5   Duration           12184 non-null  object
 6   Reaching_Time      12184 non-null  object
 7   Star_Rating        12184 non-null  float64
 8   Price              12184 non-null  float64
 9   Seat_Availability  12184 non-null  int64
dtypes: float64(2), int64(1), object(7)
memory usage: 952.0+ KB

In [2]:
# converting null
df["Price"].fillna(0)

0         444.0
1         488.0
2         720.0
3         469.0
4         720.0
          ...
12179    1799.0
12180    1999.0
12181    1999.0
12182    1050.0
12183     275.0
Name: Price, Length: 12184, dtype: float64

In [3]:
df["Star_Rating"].fillna(0)

0        2.5
1        3.2
2        4.0
3        3.0
4        3.7
        ...
12179    1.6
12180    1.6
12181    1.6
12182    1.5
12183    3.3
Name: Star_Rating, Length: 12184, dtype: float64

In [4]:
# Convert time to datetime and then format to HH:MM
df['Departing_Time'] = pd.to_datetime(df['Departing_Time'], format='%H:%M:%S').dt.strftime('%H:%M')
df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 9357,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",09:15,07h 35m,16:50:00,2.5,444.0,32
1,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 40569,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",09:40,07h 20m,17:00:00,3.2,488.0,34
2,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3634,AMARAVATHI (VOLVO / SCANIA A.C Multi Axle),10:10,05h 50m,16:00:00,4.0,720.0,36
3,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3598,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",10:35,07h 00m,17:35:00,3.0,469.0,27
4,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 35086,AMARAVATHI (VOLVO / SCANIA A.C Multi Axle),11:15,05h 45m,17:00:00,3.7,720.0,45
...,...,...,...,...,...,...,...,...,...,...
12179,Gopalganj (Bihar) to Lucknow,https://www.redbus.in/bus-tickets/gopalganj-to...,Panwar tour and Travels,A/C Seater / Sleeper (2+1),15:40,11h 50m,03:30:00,1.6,1799.0,19
12180,Gopalganj (Bihar) to Lucknow,https://www.redbus.in/bus-tickets/gopalganj-to...,Panwar tour and Travels,A/C Seater / Sleeper (2+1),15:40,11h 50m,03:30:00,1.6,1999.0,18
12181,Gopalganj (Bihar) to Lucknow,https://www.redbus.in/bus-tickets/gopalganj-to...,Travel Point World LLP,A/C Seater / Sleeper (2+2),20:20,07h 00m,03:20:00,1.6,1999.0,38
12182,Gopalganj (Bihar) to Lucknow,https://www.redbus.in/bus-tickets/gopalganj-to...,Baba Khatushyam Travels Pvt Ltd,A/C Seater / Sleeper (3+1),19:00,08h 00m,03:00:00,1.5,1050.0,56
12183,Muzaffarpur (Bihar) to Bihar Sharif,https://www.redbus.in/bus-tickets/muzaffarpur-...,Bihar state road transport corporation (BSRTC)...,AC Seater (2+2),18:00,05h 30m,23:30:00,3.3,275.0,34

In [5]:
df['Reaching_Time'] = pd.to_datetime(df['Reaching_Time'], format='%H:%M:%S').dt.strftime('%H:%M')

df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 9357,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",09:15,07h 35m,16:50,2.5,444.0,32
1,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 40569,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",09:40,07h 20m,17:00,3.2,488.0,34
2,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3634,AMARAVATHI (VOLVO / SCANIA A.C Multi Axle),10:10,05h 50m,16:00,4.0,720.0,36
3,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3598,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",10:35,07h 00m,17:35,3.0,469.0,27
4,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 35086,AMARAVATHI (VOLVO / SCANIA A.C Multi Axle),11:15,05h 45m,17:00,3.7,720.0,45
...,...,...,...,...,...,...,...,...,...,...
12179,Gopalganj (Bihar) to Lucknow,https://www.redbus.in/bus-tickets/gopalganj-to...,Panwar tour and Travels,A/C Seater / Sleeper (2+1),15:40,11h 50m,03:30,1.6,1799.0,19
12180,Gopalganj (Bihar) to Lucknow,https://www.redbus.in/bus-tickets/gopalganj-to...,Panwar tour and Travels,A/C Seater / Sleeper (2+1),15:40,11h 50m,03:30,1.6,1999.0,18
12181,Gopalganj (Bihar) to Lucknow,https://www.redbus.in/bus-tickets/gopalganj-to...,Travel Point World LLP,A/C Seater / Sleeper (2+2),20:20,07h 00m,03:20,1.6,1999.0,38
12182,Gopalganj (Bihar) to Lucknow,https://www.redbus.in/bus-tickets/gopalganj-to...,Baba Khatushyam Travels Pvt Ltd,A/C Seater / Sleeper (3+1),19:00,08h 00m,03:00,1.5,1050.0,56
12183,Muzaffarpur (Bihar) to Bihar Sharif,https://www.redbus.in/bus-tickets/muzaffarpur-...,Bihar state road transport corporation (BSRTC)...,AC Seater (2+2),18:00,05h 30m,23:30,3.3,275.0,34

In [6]:
#change dataframe to csv
path=r"C:/Users/ncssa/Downloads/bus_routes.csv"
df.to_csv(path,index=False)

In [7]:
df=pd.read_csv("C:/Users/ncssa/Downloads/bus_routes.csv")
df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 9357,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",09:15,07h 35m,16:50,2.5,444.0,32
1,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 40569,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",09:40,07h 20m,17:00,3.2,488.0,34
2,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3634,AMARAVATHI (VOLVO / SCANIA A.C Multi Axle),10:10,05h 50m,16:00,4.0,720.0,36
3,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3598,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",10:35,07h 00m,17:35,3.0,469.0,27
4,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 35086,AMARAVATHI (VOLVO / SCANIA A.C Multi Axle),11:15,05h 45m,17:00,3.7,720.0,45
...,...,...,...,...,...,...,...,...,...,...
12179,Gopalganj (Bihar) to Lucknow,https://www.redbus.in/bus-tickets/gopalganj-to...,Panwar tour and Travels,A/C Seater / Sleeper (2+1),15:40,11h 50m,03:30,1.6,1799.0,19
12180,Gopalganj (Bihar) to Lucknow,https://www.redbus.in/bus-tickets/gopalganj-to...,Panwar tour and Travels,A/C Seater / Sleeper (2+1),15:40,11h 50m,03:30,1.6,1999.0,18
12181,Gopalganj (Bihar) to Lucknow,https://www.redbus.in/bus-tickets/gopalganj-to...,Travel Point World LLP,A/C Seater / Sleeper (2+2),20:20,07h 00m,03:20,1.6,1999.0,38
12182,Gopalganj (Bihar) to Lucknow,https://www.redbus.in/bus-tickets/gopalganj-to...,Baba Khatushyam Travels Pvt Ltd,A/C Seater / Sleeper (3+1),19:00,08h 00m,03:00,1.5,1050.0,56
12183,Muzaffarpur (Bihar) to Bihar Sharif,https://www.redbus.in/bus-tickets/muzaffarpur-...,Bihar state road transport corporation (BSRTC)...,AC Seater (2+2),18:00,05h 30m,23:30,3.3,275.0,34

In [16]:
import csv
import pymysql

# Establish the connection
myconnection = pymysql.connect(host='localhost', user='root', passwd='Vinodha@123', database="redbus")
cursor = myconnection.cursor()

# Create table (if not exists to avoid errors if it already exists)
cursor.execute('''
    CREATE TABLE IF NOT EXISTS dbusdata(
        Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        Route_Name VARCHAR(255),
        Route_Link VARCHAR(255),
        Bus_Name VARCHAR(255),
        Bus_Type VARCHAR(255),
        Departing_Time VARCHAR(20),
        Duration VARCHAR(255),
        Reaching_Time VARCHAR(20),
        Star_Rating FLOAT,
        Price FLOAT,
        Seat_Availability INT
    )
''')

# Open the CSV file
with open('C:/Users/ncssa/Downloads/bus_routes.csv', newline='') as csvfile:
    csv_data = csv.reader(csvfile)
    
    # Insert rows from the CSV file into the table
    for row in csv_data:
        if row!=['Route_Name', 'Route_Link', 'Bus_Name', 'Bus_Type', 'Departing_Time', 'Duration', 'Reaching_Time', 'Star_Rating', 'Price', 'Seat_Availability']:
            
            cursor.execute('''INSERT INTO dbusdata (Route_Name, Route_Link, Bus_Name, Bus_Type, Departing_Time,
                Duration, Reaching_Time, Star_Rating, Price, Seat_Availability)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ''', row)

# Commit the transaction
myconnection.commit()

# Close the cursor and connection
cursor.close()
myconnection.close()

print("Done")

Done

In [17]:
import csv
import pymysql

# Establish the connection
myconnection = pymysql.connect(host='localhost', user='root', passwd='Vinodha@123', database="redbus")
cursor = myconnection.cursor()
query = '''select * from dbusdata;'''
cursor.execute(query)

12184

In [19]:
import pandas as pd
import pymysql
conn=pymysql.connect(host='localhost', user='root', passwd='Vinodha@123', database='redbus') 
my_cursor = conn.cursor()
query=f'''select * from dbusdata '''
my_cursor.execute(query)
out=my_cursor.fetchall()
df=pd.DataFrame(out,columns=["Id","Route_Name","Route_Link","Bus_Name","Bus_Type","Departing_time","Duration","Reaching_Time","Star_Rating","Price","Seats_Availability"])
df = df.drop(columns=['Route_Name','Route_Link','Duration'])
df

,Id,Bus_Name,Bus_Type,Departing_time,Reaching_Time,Star_Rating,Price,Seats_Availability
0,1,APSRTC - 9357,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",09:15,16:50,2.5,444.0,32
1,2,APSRTC - 40569,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",09:40,17:00,3.2,488.0,34
2,3,APSRTC - 3634,AMARAVATHI (VOLVO / SCANIA A.C Multi Axle),10:10,16:00,4.0,720.0,36
3,4,APSRTC - 3598,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",10:35,17:35,3.0,469.0,27
4,5,APSRTC - 35086,AMARAVATHI (VOLVO / SCANIA A.C Multi Axle),11:15,17:00,3.7,720.0,45
...,...,...,...,...,...,...,...,...
12179,12180,Panwar tour and Travels,A/C Seater / Sleeper (2+1),15:40,03:30,1.6,1799.0,19
12180,12181,Panwar tour and Travels,A/C Seater / Sleeper (2+1),15:40,03:30,1.6,1999.0,18
12181,12182,Travel Point World LLP,A/C Seater / Sleeper (2+2),20:20,03:20,1.6,1999.0,38
12182,12183,Baba Khatushyam Travels Pvt Ltd,A/C Seater / Sleeper (3+1),19:00,03:00,1.5,1050.0,56
12183,12184,Bihar state road transport corporation (BSRTC)...,AC Seater (2+2),18:00,23:30,3.3,275.0,34